### ISSUE TITLE
请问数据库初始脚本在哪里

### ISSUE THREAD

**Issue by scutdk** [yanghua/FixedAssetManager_Server#4]
在CentOS6.4上安装过程中也遇到了一些小小的问题，基本上都解决了。但是并没有找到数据库初始脚本，因此无法正常使用呢。

**Comment by yanghua** [comment]
已提交数据库初始化脚本：
https://github.com/yanghua/FixedAssetManager_Server/blob/master/backup/2014_01_09.sql

**Comment by scutdk** [comment]
好的。其实之前从另外一个fork里面也已经找到了~

**Comment by xiaoqi55125** [comment]
里面有个地方会发邮件备份数据库的，修改一下，最近老是收到备份邮件。。。
